import { PageSizeType } from '../types/helper';
import React from 'react';

export const pageSize: PageSizeType[] = [
  {
    name: 'Mobile Poster',
    width: 1242,
    height: 2208,
    icon: null,
    id: 'poster_mb',
    unit: 'px',
  },
  {
    name: 'Horizontal Poster',
    width: 900,
    height: 500,
    icon: null,
    id: 'poster_horizontal',
    unit: 'px',
  },
  {
    name: 'WeChat Header',
    width: 900,
    height: 383,
    icon: null,
    id: 'weixin_main',
    unit: 'px',
  },
  {
    name: 'WeChat Sub Image',
    width: 500,
    height: 500,
    icon: null,
    id: 'weixin_min',
    unit: 'px',
  },
  {
    name: 'Social Media Image',
    width: 1242,
    height: 1660,
    icon: null,
    id: 'xhs_main',
    unit: 'px',
  },
  {
    name: 'Long Article',
    width: 1000,
    height: 1500,
    icon: null,
    id: 'article_lang',
    unit: 'px',
  },
  {
    name: 'PPT (16:9)',
    width: 1242,
    height: 2208,
    icon: null,
    id: 'ppt_16_9',
    unit: 'px',
  },
  {
    name: 'Vertical Live Background',
    width: 1242,
    height: 2690,
    icon: null,
    id: 'zhibo_bg',
    unit: 'px',
  },
  {
    name: 'Vertical Video Cover',
    width: 1242,
    height: 2208,
    icon: null,
    id: 'video_poster1',
    unit: 'px',
  },
  {
    name: 'Horizontal Video Cover',
    width: 1920,
    height: 1080,
    icon: null,
    id: 'video_poster2',
    unit: 'px',
  },
  {
    name: 'Product Main Image',
    width: 800,
    height: 800,
    icon: null,
    id: 'taobao_main',
    unit: 'px',
  },
  {
    name: 'E-commerce Detail Page',
    width: 750,
    height: 1000,
    icon: null,
    id: 'taobao_detail',
    unit: 'px',
  },
  {
    name: 'PC Store Homepage',
    width: 1920,
    height: 1500,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: 'Mobile Store Homepage',
    width: 750,
    height: 1000,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: 'Store Banner',
    width: 1920,
    height: 150,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: 'E-commerce Horizontal Poster',
    width: 750,
    height: 390,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: 'E-commerce Vertical Poster',
    width: 750,
    height: 950,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: 'E-commerce Full Screen Poster',
    width: 1920,
    height: 700,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: 'Daily Quote',
    width: 1242,
    height: 2208,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: 'Mini Program Cover',
    width: 520,
    height: 416,
    icon: null,
    id: '',
    unit: 'px',
  },
  {
    name: 'Business Card',
    width: 96,
    height: 60,
    icon: null,
    id: '',
    unit: 'mm',
  },
  {
    name: 'Wall Poster',
    width: 426,
    height: 576,
    icon: null,
    id: '',
    unit: 'mm',
  },
  {
    name: '2m Roll-up Banner',
    width: 80,
    height: 200,
    icon: null,
    id: '',
    unit: 'cm',
  },
  {
    name: '1.8m Display Stand',
    width: 80,
    height: 180,
    icon: null,
    id: '',
    unit: 'cm',
  },
  {
    name: 'Coupon',
    width: 186,
    height: 66,
    icon: null,
    id: '',
    unit: 'mm',
  },
  {
    name: 'Ticket',
    width: 206,
    height: 86,
    icon: null,
    id: '',
    unit: 'mm',
  },
  {
    name: 'ID Photo',
    width: 25,
    height: 35,
    icon: null,
    id: '',
    unit: 'mm',
  },
];
